title: "The Three P's to Life-long Happiness"
author: Pangolin Mode
email: yo@pangolinmode.com
description: > # this means to ignore newlines until "baseurl:"
  Pangolin Mode has been researching pangolins for 1.9 years, almost as much time as it takes a pangolin to reach sexual maturity! Here you will find their thoughts on pangolins as well as Pokémon and other topics that begin with the letter P.
theme: minima
# social links
twitter_username: pangolinmode # DO NOT include the @ character, or else the build will fail!
github_username:  pangolinmode # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
